apiVersion: v1
kind: ConfigMap
data:
  alertmanager.yaml: |
    # alertmanager.yaml
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'sysdig-test'
    receivers:
      - name: 'sysdig-test'
        webhook_configs:
        - url: 'your url here' 
metadata:
  name: alertmanager-config
  namespace: monitoring
