apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/metrics'
      prometheus.io/port: '8080'
spec:
  selector:
    app: alertmanager
  ports:
  - name: alertmanager-dashboard
    protocol: TCP
    port: 9093
    targetPort: 9093
