apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-nfs
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.100
    path: "/media/jonjon/Spare-Drive/k8s"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc-nfs
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
---
