apiVersion: batch/v1
kind: Job
metadata:
  name: minio-import-hybris-bucket
spec:
  template:
    metadata:
      name: minio-import-hybris-bucket
    spec:
      initContainers:
      - name: wait-for-minio
        image: giantswarm/tiny-tools
        args:
        - /bin/sh
        - -c
        - >
          set -x;
          while [ $(curl -sw '%{http_code}' "http://minio.local:9000" -o /dev/null) -ne 200]; do
            echo '.'
            sleep 15;
          done
      containers:
      - name: minio-inital-data-hybris
        image: minio/mc
        command:
        - /bin/sh
        - -c
        - '/usr/bin/mc config host add hybrisminio http://minio-server:9000  ;
          /usr/bin/mc mb hybrisminio/; /usr/bin/mc policy public hybrisminio/; exit
          0;'
      restartPolicy: Never

