apiVersion: v1
kind: Service
metadata:
  labels:
    app: solr
  name: solr
spec:
  type: ClusterIP
  ports:
  - name: solr-service
    port: 8983
    targetPort: 8983
    protocol: TCP
  selector:
    app: solr