apiVersion: v1
kind: ConfigMap
data:
  10-local.properties: |
    db.url=jdbc:mysql://hybris-mysql-pxc:3306/ycomm?useConfigs=maxPerformance&characterEncoding=utf8&useSSL=false
    db.username=root
    db.password=nimda

    cluster.nodes.ping.interval=2
    cluster.nodes.stale.timeout=1

    #Mino Settings
    default.storage.strategy=s3MediaStorageStrategy
    default.url.strategy=minioS3MediaURLStrategy
    media.default.storage.strategy=s3MediaStorageStrategy
    media.default.url.strategy=minioS3MediaURLStrategy

    media.globalSettings.s3MediaStorageStrategy.bucketId=media-storage
    media.globalSettings.s3MediaStorageStrategy.accessKeyId=admin123
    media.globalSettings.s3MediaStorageStrategy.secretAccessKey=nimda123
    media.globalSettings.s3MediaStorageStrategy.endpoint=http://10.11.0.4:9000

    media.globalSettings.s3MediaStorageStrategy.url.signed=false
    media.globalSettings.s3MediaStorageStrategy.url.unsigned.https=false
    media.globalSettings.s3MediaStorageStrategy.url.unsigned.virtualHost=true
    media.globalSettings.s3MediaStorageStrategy.url.validFor=120
    media.globalSettings.s3MediaStorageStrategy.cleanOnInit=true

    cluster.nodes.autodiscovery=false
    cluster.nodes.ping.interval=200
    cluster.nodes.stale.timeout=300
    clustermode=false
    cluster.broadcast.methods=jgroups
    cluster.broadcast.method.jgroups=de.hybris.platform.cluster.jgroups.JGroupsBroadcastMethod
    cluster.broadcast.method.jgroups.channel.name=hybris-broadcast
    cluster.broadcast.method.jgroups.configuration=jgroups-tcp.xml
metadata:
  name: hybris-override-config