apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.backend: electronics.local
    traefik.backend.healthcheck.hostname: electronics.local
    traefik.backend.healthcheck.port: "9002"
    traefik.backend.healthcheck.scheme: https
    traefik.backend.loadbalancer.stickiness: "true"
    traefik.docker.network: b2c-minio_hybris
    traefik.domain: electronis.local
    traefik.enable: "true"
    traefik.frontend.entryPoints: http,https
    traefik.frontend.headers.SSLRedirect: "true"
    traefik.frontend.headers.SSLTemporaryRedirect: "true"
    traefik.frontend.redirect.entryPoint: https
    traefik.frontend.rule: Host:electronics.local,apparel-uk.local,apparel-de.local
    traefik.port: "9002"
    traefik.protocol: https
  creationTimestamp: null
  labels:
    io.kompose.service: hybris
  name: hybris
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hybris
    spec:
      containers:
      - image: pacteradeg/hybris-ootb-redis:-
        name: hybris
        ports:
        - containerPort: 9002
        resources: {}
      restartPolicy: Always
status: {}
