apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
#    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: ac967761856ac11e98f6106d60326c3c-81eae82283ab6f43.elb.ap-northeast-1.amazonaws.com
#    kubernetes.io/tls-acme: "true"
#    certmanager.k8s.io/issuer: "letsencrypt-prod"
#    certmanager.k8s.io/acme-challenge-type: http01
#    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
#    traefik.ingress.kubernetes.io/redirect-entry-point: https
#    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  name: hybris
spec:
  rules:
  - host: hybris-admin.pactera-deg.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hybris
          servicePort: 443
  - host: electronics.pactera-deg.com
    http:
      paths:
      - path: /yacceleratorstorefront
        backend:
          serviceName: hybris
          servicePort: 443
  - host: apparel-uk.pactera-deg.com
    http:
      paths:
      - path: /yacceleratorstorefront
        backend:
          serviceName: hybris
          servicePort: 443
  - host: hybris-backoffice.pactera-deg.com
    http:
      paths:
      - path: /backoffice
        backend:
          serviceName: hybris
          servicePort: 443
  tls:
  - hosts:
    - electronics.pactera-deg.com
    - apparel-uk.pactera-deg.com
    - hybris-backoffice.pactera-deg.com
    - hybris-admin.pactera-deg.com
    secretName: hybris-ssl