---
apiVersion: v1
kind: Secret
metadata:
  name: hybris-ssl
type: kubernetes.io/tls
data:
  #cat cert | base64 -w0
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVpekNDQXZPZ0F3SUJBZ0lSQU9KenFFTTVlUmFhb2h4SExENE9UdmN3RFFZSktvWklodmNOQVFFTEJRQXcKY1RFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNU013SVFZRFZRUUxEQnBRTURFeApNemM0T1Z4UU1ERXhNemM0T1VCUU1ERXhNemM0T1RFcU1DZ0dBMVVFQXd3aGJXdGpaWEowSUZBd01URXpOemc1ClhGQXdNVEV6TnpnNVFGQXdNVEV6TnpnNU1CNFhEVEU1TURJeE1EQXpNREkxTjFvWERUSTVNREl4TURBek1ESTEKTjFvd1RqRW5NQ1VHQTFVRUNoTWViV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJR05sY25ScFptbGpZWFJsTVNNdwpJUVlEVlFRTERCcFFNREV4TXpjNE9WeFFNREV4TXpjNE9VQlFNREV4TXpjNE9UQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFPbThhM2JrclZWZFFxOVlEanA1cmdNL3E1SWQrblBGeXJacW9UUFEKVUVFVjQzYU1INHJ1OWRVMjVVZE11WGtOMmZVZEZ1YVE2MThQMFkyRVJzNGNrK2RYVDVmekp2VzcxRWtZTmU5QQpLNVJiS2VJRUlnUUF2ZnBlell4VzIyKzhWZzJMeUtEaGhIWFRSWk8yenlGY3NtTGJuQ1pvWEVVZkZhd2o5MzNECkhNUmFabGdCU3k2UlhSUnhpQmRYOU5rclhBMDR4eG1xc3ppMVN3WFhja24vbXllS2dFTnROVFkvdGlHS0hQZTMKSDh5K1FMWE0xOGVta1VVV1VFdzc0d1FIaUExUnhhV2ZYL2hWQ3k1UUNHdUVLaFA0Y0N0Q1FKRDJWbUpvaXJGSQo5SDV3K3BCdkNKeW9QdFFnVnBuSVYxbE9pc3VSeUFtU3dBMU1RT3cvZ1l3K1NjOENBd0VBQWFPQndEQ0J2VEFPCkJnTlZIUThCQWY4RUJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXcKQURBZkJnTlZIU01FR0RBV2dCUkxGTEIvWEtPbWt0T0tpR1VWaGdQRU9GRFdkakJuQmdOVkhSRUVZREJlZ2h0bApiR1ZqZEhKdmJtbGpjeTV3WVdOMFpYSmhMV1JsWnk1amIyMkNIR2g1WW5KcGN5MWhaRzFwYmk1d1lXTjBaWEpoCkxXUmxaeTVqYjIyQ0lXaDVZbkpwY3kxaVlXTnJiMlptYVdObExuQmhZM1JsY21FdFpHVm5MbU52YlRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FZRUFnbUJPTUFoZEExWlRFcE9Oenk1bG8vZ1FMWE84Qis2SjNIS1FzajhJZmxZRwowZ20vR09HRzVFMzFjUDhHbHRwY0ZUTGZlUWJiaDFzaFd6WmhqdGdwZzJ4R1Q2TlIvOVgxa2pYWC9XeUZUTGxzCjUybk5oaEkxRXA0V1ZjbUJqdHlDa3FlWitneVAweXNpdUxld1E0UkFVekQ4dEFpeUhOMjl3N0laUWtSZmMyVXMKdHh5anNTY0NCaEdzSGtualpoQnJpWXNpOCtEYm8zTmwrbW1aT0cvMlJFbEpUQkMwWkQzRmM1SFBVRzMrdXJlUQoyNDNmTTBoc0U1ZGN2c3g3QkR5STdvRzJJdjIzZWhBSG9tendJcUsxVCs3YklrRU50K2NzaEtVeHRmUHZYMFhkCk9KVDJlZE9XaUNMLzZOQmxQWHBsNTlUa1labEpFMERTRC8zVWhyYzVUZ1EyV2RTS3p0cnNBNkZOUHFUTkZ0QVEKZnQ0OVZXZjkwUzQ5blQ4djJUYXVjYlVWTU1xdXpOS3NRUzFWM1hMZlZGS1NJYWFjc29VUDFISzhTMlNxWG95ZwpsZ1hqQWVCRmNuZk9ic3oyT01hWTRJcEdhbCtwT2Y5dFhyUXZiTFJFVXg0TGdrbkZGdENRWloyS1ByQ3J4N1NQCk1XblA3WlhJQzVHclpPdnNCbTFYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRHB2R3QyNUsxVlhVS3YKV0E0NmVhNERQNnVTSGZwenhjcTJhcUV6MEZCQkZlTjJqQitLN3ZYVk51VkhUTGw1RGRuMUhSYm1rT3RmRDlHTgpoRWJPSEpQblYwK1g4eWIxdTlSSkdEWHZRQ3VVV3luaUJDSUVBTDM2WHMyTVZ0dHZ2RllOaThpZzRZUjEwMFdUCnRzOGhYTEppMjV3bWFGeEZIeFdzSS9kOXd4ekVXbVpZQVVzdWtWMFVjWWdYVi9UWksxd05PTWNacXJNNHRVc0YKMTNKSi81c25pb0JEYlRVMlA3WWhpaHozdHgvTXZrQzF6TmZIcHBGRkZsQk1PK01FQjRnTlVjV2xuMS80VlFzdQpVQWhyaENvVCtIQXJRa0NROWxaaWFJcXhTUFIrY1BxUWJ3aWNxRDdVSUZhWnlGZFpUb3JMa2NnSmtzQU5URURzClA0R01Qa25QQWdNQkFBRUNnZ0VBTS9UV1RvOTJtRXNxejU5YlNsUlNBaGJkSkpYVlhuYlJJTXVER2Vsc2JZdFkKRExvSktQRUZaR2ZYZjRubWtLb3JrUGp1WmtKQWo5a01VOURiakdWOTJ5YmxZbm1DWjQxaEd2NXV2c2djNTlWNwo4ZW5KUmVxRVVHdFNkYWU1RDVWbDY0enZCQlFkUmJPNCs2VGZWaU1zNUJ5OUVTeVJsaXZhdlhFaFNxdGNjYWpaCjVWYlNBK3FER2NBQ0FHLzNxL2NPQnVGK2JUb0ZYSlhpUkZpZ3BIQm9Ma0c5VzJtSEZJZ0FLbU5KMU5uWm4zeHUKTDM5aVppMGo2QWkrWlJ5QmtDVXdUdTFmQUxSRWZaUVRYSnBTb0pPdldBM2pZbDVpTWoyUldaNWpxU3hoeVpkUwpvdW9aUlpyUmZuZHJobEJ6eC9KWWFBQmg1UjJlSDBic01ldFRZNGljd1FLQmdRRDNQTmwyZ0VIUXBKd09WZll0CklnSWxsVWd4ak5heVdiSTIvYkUyYzlSaFFLa3RzOHEyeXlkSk5LTzVQWVVNMHB0dVRraTIzdE1vc2gvRGllTjcKanpUUVpNclhHVXZqMnVkK29TZDVCQW9EN0wycEJ2ZVUvajVNY0xpcHRFSDUyZ3RteGxhQXd4eXM2dUl4eU1CKwo3Vk1Ldk9BbTJ4ZGgxM1g2S0FWekFqUXF5d0tCZ1FEeUJSSlZRL044RGU4aTNpcXJoNnFuWkdoRVVPNnJJL3NWCjBmbHc0emw3LzdxOVVCeDVyRE41clNmVG9OTjlPOUp6S1VmdEU5b2VyWE9PRCtWS2Fpa3EzUUZHVGlHZ29rU2YKaEorbGtMS0dHdWd5SHNjbFRtWndLVnl6dW9mN1BYaWZSeUYwVUdmZ3dVMG1yeFNaL3hCdzFWS1FFeE96dlNFQgpUZDExNHhrb2pRS0JnQkhYRVRZTTBUTDEvZERIQVNtR2o3TVlqNG9MeUo0Ny9MRWRJMEZ6b0RxWVNOemtZVmRKClYzOWZ6Z1NhM05QdENvd3VGKzhpS3doL3VlMEpNU0lFVm1KSE01L0wwbjhSbDZ5NmdqZW9RL1MraTN6NzVMZWEKbFBJOUhBWWEzTHZqc1Bqc2pPZGpyTmtKWmVNRHdtZ21SZHk3ZmswdmVBTjJZYXY0WVZSSUwyMTdBb0dBSFVNbgp1RStDL1JqaU5TRVBuN1hEbUlHM2Fhc3ZjRm5sWGZvSll2RFdYbnZKSkdLdlRyYlhjbnJST2ZGVUlPdyt3ZFhYCjhINVovU09UdVRXS3o3aU9TYlIzRnYwVGE4eXk1MmF0dHVNTDh0TUdDQ2xZZ3RZNzVJdmJ2WTlzS2FDQkdTRU0KbG5leVY2YUhvWW5Cdit6ckcvbHZCaVNJV1U4ZzBudUxyMWxLRFhFQ2dZRUE5ck9GTllQNmJjdUFMWXRUZVhBTAovNHNJellJbnUwdGJiQ1VXS2d2RXdwM0gweHk2THRPQWp0WEg1YkZFenREejBNZTlQZzhhL1NoaXdDRTJxWm56Ck9iYXBoak9MeHVkVDV4b3lXZlF1c0NnbGpmTjM3T3JGQTJJZXlvNldUclRYak51ZkZoTVdBTHZCL2ZXUmU5VGMKcWVETkFuQWdqTzk2ZVF5eDhURjdrQ009Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: ConfigMap
data:
  local.properties: |
    #########################################################################################################
    #########################################################################################################
    ##################################### START CUSTOM PROPERTIES ###########################################
    #########################################################################################################
    #########################################################################################################

    #### DATABASE ####
    ## A type of MySQL database tables, for example InnoDB for transactional or MyISAM for non-transactional tables
    #mysql.tabletype=InnoDB

    #db.url=jdbc:mysql://mysql:3306/ycomm?useConfigs=maxPerformance&characterEncoding=utf8&useSSL=false
    #db.driver=com.mysql.jdbc.Driver
    #db.username=root
    #db.password=nimda
    #db.tableprefix=
    #mysql.optional.tabledefs=CHARSET=utf8 COLLATE=utf8_bin
    #mysql.allow.fractional.seconds=true

    ## Setting proper transaction isolation level is required for MySQL
    #db.customsessionsql=SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

    ## Default solr in standalone mode
    #solrserver.instances.default.autostart=false
    #solrserver.instances.default.mode=standalone
    #solrserver.instances.default.hostname=solr
    #solrserver.instances.default.port=8983
    #solrserver.instances.default.memory=512m
    #solrserver.instances.default.authtype=basic
    #solrserver.instances.default.user=solradmin
    #solrserver.instances.default.password=admin123
    #solrserver.instances.default.ssl.enabled=true
    #solrserver.instances.default.ssl.keyStorePassword=123456
    #solrserver.instances.default.ssl.trustStorePassword=123456

    #Mino Settings
    #default.storage.strategy=s3MediaStorageStrategy
    #default.url.strategy=minioS3MediaURLStrategy
    #media.default.storage.strategy=s3MediaStorageStrategy
    #media.default.url.strategy=minioS3MediaURLStrategy

    #media.globalSettings.s3MediaStorageStrategy.bucketId=media-storage
    #media.globalSettings.s3MediaStorageStrategy.accessKeyId=admin123
    #media.globalSettings.s3MediaStorageStrategy.secretAccessKey=nimda123
    #media.globalSettings.s3MediaStorageStrategy.endpoint=http://10.11.0.4:9000

    #media.globalSettings.s3MediaStorageStrategy.url.signed=false
    #media.globalSettings.s3MediaStorageStrategy.url.unsigned.https=false
    #media.globalSettings.s3MediaStorageStrategy.url.unsigned.virtualHost=true
    #media.globalSettings.s3MediaStorageStrategy.url.validFor=120
    #media.globalSettings.s3MediaStorageStrategy.cleanOnInit=true

    #cluster.nodes.autodiscovery=true
    #cluster.nodes.ping.interval=200
    #cluster.nodes.stale.timeout=300
    #clustermode=true
    #cluster.broadcast.methods=jgroups
    #cluster.broadcast.method.jgroups=de.hybris.platform.cluster.jgroups.JGroupsBroadcastMethod
    #cluster.broadcast.method.jgroups.channel.name=hybris-broadcast
    #cluster.broadcast.method.jgroups.configuration=jgroups-tcp.xml

    #########################################################################################################
    #########################################################################################################
    #################################### END CUSTOM PROPERTIES ##############################################
    #########################################################################################################
    #########################################################################################################
metadata:
  name: hybris-config
---
apiVersion: v1
kind: ConfigMap
data:
  10-local.properties: |
    #mysql.tabletype=InnoDB

    db.url=jdbc:mysql://mysql.mysql.svc.cluster.local:3306/ycomm?useConfigs=maxPerformance&characterEncoding=utf8&useSSL=false
    db.driver=com.mysql.jdbc.Driver
    db.username=root
    db.password=nimda
    #db.tableprefix=
    mysql.optional.tabledefs=CHARSET=utf8 COLLATE=utf8_bin
    mysql.allow.fractional.seconds=true

    ## Setting proper transaction isolation level is required for MySQL
    db.customsessionsql=SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

    #db.url=jdbc:hsqldb:file:${HYBRIS_DATA_DIR}/hsqldb/mydb;shutdown=true;hsqldb.tx=MVCC
    #db.driver=org.hsqldb.jdbcDriver
    #db.username=sa
    #db.password=
    #db.tableprefix=
    #hsqldb.usecachedtables=true

    cluster.nodes.ping.interval=2
    cluster.nodes.stale.timeout=1

    #Mino Settings
    default.storage.strategy=s3MediaStorageStrategy
    default.url.strategy=minioS3MediaURLStrategy
    media.default.storage.strategy=s3MediaStorageStrategy
    media.default.url.strategy=minioS3MediaURLStrategy

    media.globalSettings.s3MediaStorageStrategy.bucketId=media-storage
    media.globalSettings.s3MediaStorageStrategy.accessKeyId=admin123
    media.globalSettings.s3MediaStorageStrategy.secretAccessKey=nimda123
    #media.globalSettings.s3MediaStorageStrategy.endpoint=http://10.11.0.4:9000
    #media.globalSettings.s3MediaStorageStrategy.endpoint=http://pactera-minio-s3.minio-mgnzn.svc.cluster.local:9000
    #media.globalSettings.s3MediaStorageStrategy.endpoint=https://minio.pactera-deg.com
    media.globalSettings.s3MediaStorageStrategy.endpoint=http://10.42.2.7:9000
    media.globalSettings.s3MediaStorageStrategy.url.signed=false
    media.globalSettings.s3MediaStorageStrategy.url.unsigned.https=false
    media.globalSettings.s3MediaStorageStrategy.url.unsigned.virtualHost=true
    media.globalSettings.s3MediaStorageStrategy.url.validFor=120
    media.globalSettings.s3MediaStorageStrategy.cleanOnInit=true

    media.globalSettings.s3MediaStorageStrategy.dockerFrontFacingEndpoint=https://minio.pactera-deg.com

    #cluster.nodes.autodiscovery=false
    #cluster.nodes.ping.interval=200
    #cluster.nodes.stale.timeout=300
    #clustermode=false
    #cluster.broadcast.methods=jgroups
    #cluster.broadcast.method.jgroups=de.hybris.platform.cluster.jgroups.JGroupsBroadcastMethod
    #cluster.broadcast.method.jgroups.channel.name=hybris-broadcast
    #cluster.broadcast.method.jgroups.configuration=jgroups-tcp.xml
metadata:
  name: hybris-override-config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hybris
  name: hybris
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hybris
    spec:
      containers:
        - name: hybris
          image: pacteradeg/hybris-ootb:b2c-minio-1808
          env:
          - name: PLATFORM_HOME
            value: /opt/hybris/bin/platform
          - name: HYBRIS_OPT_CONFIG_DIR
            value: /opt/hybris/config/override
          - name: HYBRIS_OPT_CONFIG
            value: /opt/hybris/config/override
          ports:
          - containerPort: 9002
          resources: {}
          securityContext:
            runAsUser: 1000
          volumeMounts:
          - name: hybris-config
            mountPath: /opt/hybris/config/local.properties
            subPath: local.properties
          - name: hybris-override
            mountPath: /opt/hybris/config/override/10-local.properties
            subPath: 10-local.properties
      volumes:
        - name: hybris-config
          configMap:
            name: hybris-config
        - name: hybris-override
          configMap:
            name: hybris-override-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hybris
  name: hybris
spec:
  type: ClusterIP
  ports:
  - name: hybris
    port: 443
    targetPort: 9002
  selector:
    app: hybris
