apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik.k8s-pactera-deg.com.
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: traefik
    release: traefik
  sessionAffinity: None
  type: LoadBalancer