apiVersion: v1
kind: ConfigMap
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "DEBUG"
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
            certFile = "/ssl/traefik-dashboard.local.crt"
            keyFile = "/ssl/traefik-dashboard.local.key"
      compress = true
      [entryPoints.traefik]
      address = ":8080"
    [kubernetes]
    namespaces = ["default", "kube-system"]
    [traefikLog]
      format = "json"
    [api]
      entryPoint = "traefik"
      dashboard = true
    [metrics]
      [metrics.prometheus]
        buckets = [0.1,0.3,1.2,5.0]
metadata:
  name: traefik
  namespace: default
